[package]
name = "llama2-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
ndarray = "0.15"
# x86_64 only
# ndarray-linalg = "0.16"

